docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin  $CI_REGISTRY
  script:
    - umask
    - ls -lR
    - umask 0022
    - umask
    - chmod -R og-w .
    - docker build -t jgoerzen/weewx .
    - docker tag jgoerzen/weewx jgoerzen/weewx:4.10.2
    - docker push jgoerzen/weewx
    - docker push jgoerzen/weewx:4.10.2
  only:
    - master

